In [17]:
import pandas as pd
orders = pd.read_csv('../data/orders.csv')
orders

,order_id,product_id,customer_id,quantity_ordered,quantity_delivered,order_date,expected_delivery_date,actual_delivery_date,order_status
0,ORD-0001,PROD-010,CUST-005,20,20.0,2026-01-05,2026-01-12,2026-01-11,Delivered
1,ORD-0002,PROD-003,CUST-002,5,NaN,2026-01-06,2026-01-13,NaN,Pending
2,ORD-0003,PROD-007,CUST-001,15,12.0,2026-01-07,2026-01-14,2026-01-13,Delivered
3,ORD-0004,PROD-002,CUST-004,10,7.0,2026-01-08,2026-01-15,2026-01-17,Delivered
4,ORD-0005,PROD-005,CUST-009,8,NaN,2026-01-09,2026-01-16,NaN,Cancelled
5,ORD-0006,PROD-001,CUST-006,12,NaN,2026-01-10,2026-01-17,NaN,Delayed
6,ORD-0007,PROD-004,CUST-007,25,20.0,2026-01-11,2026-01-18,2026-01-21,Delivered
7,ORD-0008,PROD-008,CUST-008,30,NaN,2026-01-12,2026-01-19,NaN,Pending
8,ORD-0009,PROD-009,CUST-009,18,18.0,2026-01-13,2026-01-20,2026-01-20,Delivered
9,ORD-0010,PROD-007,CUST-010,22,NaN,2026-01-14,2026-01-21,NaN,Delayed
10,ORD-0011,PROD-010,CUST-011,14,14.0,2026-01-15,2026-01-22,2026-01-23,Delivered
11,ORD-0012,PROD-012,CUST-012,7,NaN,2026-01-16,2026-01-23,NaN,Pending

In [18]:
orders.head()

,order_id,product_id,customer_id,quantity_ordered,quantity_delivered,order_date,expected_delivery_date,actual_delivery_date,order_status
0,ORD-0001,PROD-010,CUST-005,20,20.0,2026-01-05,2026-01-12,2026-01-11,Delivered
1,ORD-0002,PROD-003,CUST-002,5,NaN,2026-01-06,2026-01-13,NaN,Pending
2,ORD-0003,PROD-007,CUST-001,15,12.0,2026-01-07,2026-01-14,2026-01-13,Delivered
3,ORD-0004,PROD-002,CUST-004,10,7.0,2026-01-08,2026-01-15,2026-01-17,Delivered
4,ORD-0005,PROD-005,CUST-009,8,NaN,2026-01-09,2026-01-16,NaN,Cancelled

In [19]:
orders.describe()

       quantity_ordered  quantity_delivered
count          12.00000            6.000000
mean           15.50000           15.166667
std             7.70478            5.154286
min             5.00000            7.000000
25%             9.50000           12.500000
50%            14.50000           16.000000
75%            20.50000           19.500000
max            30.00000           20.000000

In [20]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                12 non-null     str
 1   product_id              12 non-null     str
 2   customer_id             12 non-null     str
 3   quantity_ordered        12 non-null     int64
 4   quantity_delivered      6 non-null      float64
 5   order_date              12 non-null     str
 6   expected_delivery_date  12 non-null     str
 7   actual_delivery_date    6 non-null      str
 8   order_status            12 non-null     str
dtypes: float64(1), int64(1), str(7)
memory usage: 996.0 bytes

In [21]:
orders['order_date'] = pd.to_datetime(orders['order_date'])
orders['expected_delivery_date'] = pd.to_datetime(orders['expected_delivery_date'])
orders['actual_delivery_date'] = pd.to_datetime(orders['actual_delivery_date'])

In [22]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                12 non-null     str
 1   product_id              12 non-null     str
 2   customer_id             12 non-null     str
 3   quantity_ordered        12 non-null     int64
 4   quantity_delivered      6 non-null      float64
 5   order_date              12 non-null     datetime64[us]
 6   expected_delivery_date  12 non-null     datetime64[us]
 7   actual_delivery_date    6 non-null      datetime64[us]
 8   order_status            12 non-null     str
dtypes: datetime64[us](3), float64(1), int64(1), str(4)
memory usage: 996.0 bytes

In [23]:
orders['delivery_delay_days'] = (orders['actual_delivery_date'] - orders['expected_delivery_date']).dt.days
orders

,order_id,product_id,customer_id,quantity_ordered,quantity_delivered,order_date,expected_delivery_date,actual_delivery_date,order_status,delivery_delay_days
0,ORD-0001,PROD-010,CUST-005,20,20.0,2026-01-05,2026-01-12,2026-01-11,Delivered,-1.0
1,ORD-0002,PROD-003,CUST-002,5,NaN,2026-01-06,2026-01-13,NaT,Pending,NaN
2,ORD-0003,PROD-007,CUST-001,15,12.0,2026-01-07,2026-01-14,2026-01-13,Delivered,-1.0
3,ORD-0004,PROD-002,CUST-004,10,7.0,2026-01-08,2026-01-15,2026-01-17,Delivered,2.0
4,ORD-0005,PROD-005,CUST-009,8,NaN,2026-01-09,2026-01-16,NaT,Cancelled,NaN
5,ORD-0006,PROD-001,CUST-006,12,NaN,2026-01-10,2026-01-17,NaT,Delayed,NaN
6,ORD-0007,PROD-004,CUST-007,25,20.0,2026-01-11,2026-01-18,2026-01-21,Delivered,3.0
7,ORD-0008,PROD-008,CUST-008,30,NaN,2026-01-12,2026-01-19,NaT,Pending,NaN
8,ORD-0009,PROD-009,CUST-009,18,18.0,2026-01-13,2026-01-20,2026-01-20,Delivered,0.0
9,ORD-0010,PROD-007,CUST-010,22,NaN,2026-01-14,2026-01-21,NaT,Delayed,NaN
10,ORD-0011,PROD-010,CUST-011,14,14.0,2026-01-15,2026-01-22,2026-01-23,Delivered,1.0
11,ORD-0012,PROD-012,CUST-012,7,NaN,2026-01-16,2026-01-23,NaT,Pending,NaN

In [24]:
mask = orders['order_status'] == 'Delivered' 
delivered_orders = orders[mask]
# delivered_orders = orders[orders['orders_status'] == 'delivered']
delivered_orders

,order_id,product_id,customer_id,quantity_ordered,quantity_delivered,order_date,expected_delivery_date,actual_delivery_date,order_status,delivery_delay_days
0,ORD-0001,PROD-010,CUST-005,20,20.0,2026-01-05,2026-01-12,2026-01-11,Delivered,-1.0
2,ORD-0003,PROD-007,CUST-001,15,12.0,2026-01-07,2026-01-14,2026-01-13,Delivered,-1.0
3,ORD-0004,PROD-002,CUST-004,10,7.0,2026-01-08,2026-01-15,2026-01-17,Delivered,2.0
6,ORD-0007,PROD-004,CUST-007,25,20.0,2026-01-11,2026-01-18,2026-01-21,Delivered,3.0
8,ORD-0009,PROD-009,CUST-009,18,18.0,2026-01-13,2026-01-20,2026-01-20,Delivered,0.0
10,ORD-0011,PROD-010,CUST-011,14,14.0,2026-01-15,2026-01-22,2026-01-23,Delivered,1.0

In [25]:
on_time_mask = delivered_orders['delivery_delay_days'] <= 0
total_delivered = len(delivered_orders)
on_time_rate = (on_time_mask.sum() / total_delivered) * 100
on_time_rate
print(f"On-Time Delivery Rate: {on_time_rate:.1f}%")

On-Time Delivery Rate: 50.0%

In [26]:
orders.info()
orders

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                12 non-null     str
 1   product_id              12 non-null     str
 2   customer_id             12 non-null     str
 3   quantity_ordered        12 non-null     int64
 4   quantity_delivered      6 non-null      float64
 5   order_date              12 non-null     datetime64[us]
 6   expected_delivery_date  12 non-null     datetime64[us]
 7   actual_delivery_date    6 non-null      datetime64[us]
 8   order_status            12 non-null     str
 9   delivery_delay_days     6 non-null      float64
dtypes: datetime64[us](3), float64(2), int64(1), str(4)
memory usage: 1.1 KB

,order_id,product_id,customer_id,quantity_ordered,quantity_delivered,order_date,expected_delivery_date,actual_delivery_date,order_status,delivery_delay_days
0,ORD-0001,PROD-010,CUST-005,20,20.0,2026-01-05,2026-01-12,2026-01-11,Delivered,-1.0
1,ORD-0002,PROD-003,CUST-002,5,NaN,2026-01-06,2026-01-13,NaT,Pending,NaN
2,ORD-0003,PROD-007,CUST-001,15,12.0,2026-01-07,2026-01-14,2026-01-13,Delivered,-1.0
3,ORD-0004,PROD-002,CUST-004,10,7.0,2026-01-08,2026-01-15,2026-01-17,Delivered,2.0
4,ORD-0005,PROD-005,CUST-009,8,NaN,2026-01-09,2026-01-16,NaT,Cancelled,NaN
5,ORD-0006,PROD-001,CUST-006,12,NaN,2026-01-10,2026-01-17,NaT,Delayed,NaN
6,ORD-0007,PROD-004,CUST-007,25,20.0,2026-01-11,2026-01-18,2026-01-21,Delivered,3.0
7,ORD-0008,PROD-008,CUST-008,30,NaN,2026-01-12,2026-01-19,NaT,Pending,NaN
8,ORD-0009,PROD-009,CUST-009,18,18.0,2026-01-13,2026-01-20,2026-01-20,Delivered,0.0
9,ORD-0010,PROD-007,CUST-010,22,NaN,2026-01-14,2026-01-21,NaT,Delayed,NaN
10,ORD-0011,PROD-010,CUST-011,14,14.0,2026-01-15,2026-01-22,2026-01-23,Delivered,1.0
11,ORD-0012,PROD-012,CUST-012,7,NaN,2026-01-16,2026-01-23,NaT,Pending,NaN

In [27]:
total_ordered = delivered_orders['quantity_ordered'].sum()
total_delivered_units = delivered_orders['quantity_delivered'].sum()
fill_rate = (total_delivered_units / total_ordered) * 100
print(f"Fill Rate: {fill_rate:.1f}%")

Fill Rate: 89.2%

In [28]:
currently_delayed_count = (orders['order_status'] == 'Delayed').sum()
delivered_late_count = (delivered_orders['delivery_delay_days'] > 0).sum()

print(f"Currently Delayed (in-progress): {currently_delayed_count}")
print(f"Delivered Late (historical): {delivered_late_count}")

Currently Delayed (in-progress): 2
Delivered Late (historical): 3